apiVersion: v1
kind: Service
metadata:
  name: project-python-test
spec:
  selector:
    app: project-python-test
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
      nodePort: 30000
